[tool.poetry]
name = "oncodashkb"
version = "0.1.0"
description = "Knowledge graph build for oncodash using BioCypher"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
biocypher = "^0.6.1"
ontoweaver = "^0.1.1"
pooch = "^1.7.0"
pandas = "^2.0.1"
owlready2 = "^0.47"
pyarrow = "^18.1.0"
numpy = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
