########################################
# IDENTIFICATION
########################################

sequence variant:
    represented_as: node
    label_in_input: variant

patient has variant: # Not existing in our ontology…
    # … thus added by Biocypher under:
    is_a: case to phenotypic feature association
    represented_as: edge
    label_in_input: patient_has_variant
    source: patient
    target: sequence variant

# PATIENT
# =======

patient: # Existing in Biolink.
    represented_as: node
    label_in_input: patient
    synonym_for: case

# sample:
#   synonym_for: material sample
#   represented_as: node
#   label_in_input: sample

# OMICS
# =====

genome:
    represented_as: node
    label_in_input: genome

reference genome:
    is_a: genotype to phenotypic feature association
    represented_as: edge
    label_in_input: reference_genome
    source: phenotypic feature
    target: genome

gene:
    represented_as: node
    preferred_id: [gene_hugo, gene_entrez]
    label_in_input: [gene_hugo, gene_entrez]

variant to gene association:
    is_a: association
    represented_as: edge
    label_in_input: variant_in_gene


# gene:
#   represented_as: node
#   label_in_input: gene

# protein:
#   represented_as: node
#   label_in_input: protein

# small molecule:
#   represented_as: node
#   label_in_input: molecule


# # DISEASE
# # =======

# disease:
#   represented_as: node
#   label_in_input: disease

# tumour type:
#   is_a: phenotypic feature  # clinical finding?
#   represented_as: node
#   label_in_input: tumour

# ########################################
# # ONCOGENECITY
# ########################################

# ########################################
# # VARIANTS
# ########################################

# ########################################
# # ALTERATION <-> BIOMARKER
# ########################################

# ########################################
# # RESPONSE
# ########################################

# ########################################
# # SOURCE
# ########################################

# ########################################
# # DRUG
# ########################################

# drug:
#   represented_as: node
#   label_in_input: drug

# ########################################
# # EVIDENCE
# ########################################

# confidence level:
#   represented_as: node
#   preferred_id: [vicc, escat]
#   label_in_input: [cgi, mtbp]

# biomarker variant:
#   is_a: sequence variant
#   represented_as: node
#   label_in_input: biomarker

# missense variant:
#   represented_as: node
#   label_in_input: Missense

# # Relations

# sequence variant to biomarker variant association:
#   is_a: association
#   represented_as: edge
#   label_in_input: variant_to_biomarker

# drug to biomarker variant association:
#   is_a: association
#   represented_as: node
#   label_in_input: drug_to_biomarker

# confidence level to drug to biomarker variant association:
#   is_a: association
#   represented_as: edge
#   label_as_edge: HAS_CONFIDENCE_LEVEL
#   source: confidence level
#   target: drug to sequence variant association
#   label_in_input: confidence_level_to_drug_to_biomarker

# confidence level to confidence level association:
#   is_a: association
#   represented_as: edge
#   label_in_input: confidence_level_to_confidence_level
