########################################
# IDENTIFICATION
########################################

sequence variant:
    represented_as: node
    label_in_input: variant
    properties:
        timestamp: str

# PATIENT
# =======

patient: # Existing in Biolink.
    represented_as: node
    label_in_input: patient
    synonym_for: case

patient has variant: # Not existing in Biolink…
    # … thus added by Biocypher under:
    is_a: case to phenotypic feature association
    represented_as: edge
    label_in_input: patient_has_variant
    source: sequence variant
    target: patient


# OMICS
# =====

genome:
    represented_as: node
    label_in_input: genome

reference genome:
    is_a: genotype to phenotypic feature association
    represented_as: edge
    label_in_input: reference_genome
    source: sequence variant
    target: genome


gene:
    represented_as: node
    input_label: gene_hugo
    properties:
        entrez_gene_id: str

variant to gene association:
    is_a: association
    represented_as: edge
    label_in_input: variant_in_gene


# DISEASE
# =======

disease:
  represented_as: node
  label_in_input: disease

variant to disease association:
    is_a: association
    represented_as: edge
    label_in_input: variant_to_disease
    source: sequence variant
    target: disease


oncogenicity: # Not in Biolink
    is_a: behavioral feature
    represented_as: node
    label_in_input: oncogenicity

variant to oncogenicity:
    is_a: variant to phenotypic feature association
    represented_as: edge
    label_in_input: variant_to_oncogenicity
    source: sequence variant
    target: oncogenicity


# ########################################
# # ALTERATION <-> BIOMARKER
# ########################################

# ########################################
# # RESPONSE
# ########################################

# ########################################
# # SOURCE
# ########################################

# ########################################
# # DRUG
# ########################################

# drug:
#   represented_as: node
#   label_in_input: drug

# ########################################
# # EVIDENCE
# ########################################

# confidence level:
#   represented_as: node
#   preferred_id: [vicc, escat]
#   label_in_input: [cgi, mtbp]

# biomarker variant:
#   is_a: sequence variant
#   represented_as: node
#   label_in_input: biomarker

# missense variant:
#   represented_as: node
#   label_in_input: Missense

# # Relations

# sequence variant to biomarker variant association:
#   is_a: association
#   represented_as: edge
#   label_in_input: variant_to_biomarker

# drug to biomarker variant association:
#   is_a: association
#   represented_as: node
#   label_in_input: drug_to_biomarker

# confidence level to drug to biomarker variant association:
#   is_a: association
#   represented_as: edge
#   label_as_edge: HAS_CONFIDENCE_LEVEL
#   source: confidence level
#   target: drug to sequence variant association
#   label_in_input: confidence_level_to_drug_to_biomarker

# confidence level to confidence level association:
#   is_a: association
#   represented_as: edge
#   label_in_input: confidence_level_to_confidence_level
