########################
# NODES
########################


alteration:
    is_a: sequence variant
    represented_as: node
    label_in_input: alteration


########################
# EDGES
########################

## CAUSAL LINKS
## Everything that derivates from the "causes" link type.
## Comprises both real causes and ownership ("carries").

### CARRIES

# To allow queries for patient carrying samples, and samples carrying alterations,
# without mixing with "effects" causes.
carries:
    is_a: causes
    represented_as: edge
    label_in_input: carries

patient carries sample:
    is_a: carries
    represented_as: edge
    label_in_input: patient carries sample
    source: patient
    target: sample

sample carries alteration:
    is_a: carries
    represented_as: edge
    label_in_input: sample carries alteration
    source: sample
    target: alteration


### CAUSES

# A gene is linked to its functional effects (gain or loss of function),
# which are represented as nodes, so as to allow a causal path
# to go through alteration -> gene effect -> transcript activity.
# Hence, effects have at least two instances:
# - Gene:GoF, and
# - Gene:LoF.
# Same for proteins with:
# - Transcrit:Active, and
# - Transcript:Inactive.
# Incidentally: the source of an edge of type "causes"
# cannot be an inactive protein.

alteration causes effect:
    is_a: causes
    represented_as: edge
    label_in_input: alteration causes effect
    source: alteration
    target: functional effect

effect causes change of protein activity:
    is_a: causes
    represented_as: edge
    label_in_input: effect causes change of protein activity
    source: functional effect
    target: activity change

# probelm affected by is inverse of affects which is at the same level as causes
alteration affected by drug:
    is_a: causes
    represented_as: edge
    label_in_input: alteration affected by drug
    source: alteration
    target: drug

## METADATA

### AFFECTS

alteration affects gene:
    is_a: affects
    represented as:edge
    label_in_input: alteration affects gene
    source: alteration
    taregt: gene

functional effect affects gene:
    is_a: affects
    represented_as: edge
    label_in_input: functional effect affects gene
    source: functional effect
    target: gene

# # it would be the opposite of alteration affects gene
# gene has alteration:
#     is_a: has sequence variant
#     represented_as: edge
#     label_in_input: gene has alteration
#     source: gene
#     target: alteration

change of activity affects transcript:
    is_a: affects
    represented_as: edge
    label_in_input: change of activity affects transcript
    source: change of activity
    target: transcript


## ???? (SYSBIO)

transcribed to: # in Biolink (under "related to at instance level")
    represented_as: edge
    label_in_input: transcribed to
    source: gene
    target: transcript

